### ISSUE TITLE
Configurable random images on home page

### ISSUE THREAD

**Issue by jackrosenthal** [ColoradoSchoolOfMines/acm-website#26]
Need to provide a database model for home page images (via depot) & descriptions

Select randomly when the page is loaded

**Comment by edwargix** [comment]
Will the image be random for each visitor of the site or will the image change on a time basis (eg day-by-day)?

**Comment by sumnerevans** [comment]
@edwargix , maybe that should be a configuration option. Something like `randomization_strategy`.

CC: @jackrosenthal

**Comment by jackrosenthal** [comment]
Random per page load. No need to over-complicate.

**Comment by sumnerevans** [comment]
@edwargix, To specify which images are used, we could just add a config option (something like `homepage_image_dir`) which will contain the images that we use for the randomization. I don't think this needs to be an entire DB table.

CC: @jackrosenthal

**Comment by jackrosenthal** [comment]
> To specify which images are used, we could just add a config option (something like homepage_image_dir) which will contain the images that we use for the randomization. I don't think this needs to be an entire DB table.

Disagree. This would fit very elegantly as a database table with the images stored as Depot files. It allows for descriptions to be stored side by side with the images (how do you plan on doing this with the FS?), as well as allows for easy addition of images from admin panel. Using the file system would just be _nasty_!

**Comment by sumnerevans** [comment]
> It allows for descriptions to be stored side by side with the images (how do you plan on doing this with the FS?)

Ah, yes. Didn't consider the descriptions. Database table with Depot it is.
