### ISSUE TITLE
Allow meetings to have duration

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/acm-website#27]
- [x] Add duration to the Meeting database model
- [x] Show it on the schedule page?
- [x] Use the duration to specify the duration of the event on the iCal. (See #22)

**Comment by jackrosenthal** [comment]
Show duration on schedule page **only if** it's not the default 2 hours.

Should be shown as a time range (_t_ to _t_ + _d_, rather than just _d_).

**Comment by jackrosenthal** [comment]
Default duration is now specified as `meetings.default_duration` in the paste config.

**Comment by sumnerevans** [comment]
@jackrosenthal, this is ready for deployment.
