### ISSUE TITLE
iCalendar schedule in wrong time zone

### ISSUE THREAD

**Issue by jackrosenthal** [ColoradoSchoolOfMines/acm-website#28]
Google Calendar seems to think the timezone is UTC

**Comment by sumnerevans** [comment]
I'm not being able to reproduce this. Does it only occur when you use the import from URL functionality? I've only been able to test by downloading the `.ics` and then uploading it to Google Calendar.

**Comment by sumnerevans** [comment]
Still not working for me. It appears that we also need to set the timezone on the calendar object itself?

**Comment by jackrosenthal** [comment]
Nope... you are receiving a cached version from this morning. Google Calendar's fault.

Add some random garbage in the query string to fix for now.
